spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: clone
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${PORT}